//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_API_SEBO.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class article
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public article()
        {
            this.ligne_de_commande = new HashSet<ligne_de_commande>();
        }
    
        public string reference { get; set; }
        public string titre { get; set; }
        public string editeur { get; set; }
        public string auteur { get; set; }
        public string description { get; set; }
        public double prix { get; set; }
        public string image { get; set; }
        public bool reassort { get; set; }
        public int qteStock { get; set; }
        public int qteCommande { get; set; }
        public string type { get; set; }
        public string NomPromo { get; set; }
        public Nullable<int> idCommande { get; set; }
    
        public virtual genre genre { get; set; }
        public virtual promo promo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ligne_de_commande> ligne_de_commande { get; set; }
    }
}
