//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_API_SEBO.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class livraison
    {
        public int idLivraison { get; set; }
        public Nullable<System.DateTime> dateLivraison { get; set; }
        public string numeroAR { get; set; }
        public int idCommande { get; set; }
    
        public virtual commande commande { get; set; }
    }
}
