//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_API_SEBO.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sebocestpasbeauEntities3 : DbContext
    {
        public sebocestpasbeauEntities3()
            : base("name=sebocestpasbeauEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<adresse> adresse { get; set; }
        public virtual DbSet<article> article { get; set; }
        public virtual DbSet<categorie> categorie { get; set; }
        public virtual DbSet<client> client { get; set; }
        public virtual DbSet<commande> commande { get; set; }
        public virtual DbSet<genre> genre { get; set; }
        public virtual DbSet<ligne_de_commande> ligne_de_commande { get; set; }
        public virtual DbSet<livraison> livraison { get; set; }
        public virtual DbSet<promo> promo { get; set; }
    }
}
