//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_REST_SEBO.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ligne_de_commande
    {
        public int idCommande { get; set; }
        public string reference { get; set; }
        public int qte { get; set; }
    
        public virtual article article { get; set; }
        public virtual commande commande { get; set; }
    }
}
